name: Run Sorting Benchmark with Timeout and All CPUs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 480 # Adjust if needed
    env:
      USE_ALL_CPUS: "true" # Use all available CPU cores
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Optionally install from requirements.txt if it exists:
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Sorting Benchmark with Timeout
        run: |
          # Provide blank input for iterations (default used), '5' for the time threshold,
          # then 'y' to enable per-run timeouts.
          printf "\n5\ny\n" | python main.py

      - name: Archive Markdown Files
        run: |
          # Archive README.md, details.md, and all markdown files in results/algorithms/ into a ZIP archive.
          zip -r markdown-files.zip README.md details.md results/algorithms/

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "benchmark-$(date +'%Y%m%d%H%M%S')"
          release_name: "Sorting Benchmark $(date +'%Y-%m-%d %H:%M:%S')"
          body: |
            Automated benchmark run for sorting algorithms with per-run timeouts enabled (5s per iteration)
            and all CPU cores used. See attached markdown archive for results.
          draft: false
          prerelease: false

      - name: Upload Benchmark Results as Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: markdown-files.zip
          asset_name: markdown-files.zip
          asset_content_type: application/zip
