name: Run Sorting Benchmark with Timeout and All CPUs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 60 # Adjust if needed
    env:
      USE_ALL_CPUS: "true" # Let your code know to use all available CPU cores
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Sorting Benchmark with Timeout
        run: |
          # Pipe blank inputs for iterations and threshold, then 'y' to enable timeout and '10' as the per-run timeout.
          printf "\n\ny\n10\n" | python main.py

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "benchmark-$(date +'%Y%m%d%H%M%S')"
          release_name: "Sorting Benchmark $(date +'%Y-%m-%d %H:%M:%S')"
          body: "Automated benchmark run for sorting algorithms with timeout enabled and all CPU cores used. See attached README.md for results."
          draft: false
          prerelease: false

      - name: Upload Benchmark Results as Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: README.md
          asset_name: README.md
          asset_content_type: text/markdown
